// What is javascript

/* 

JavaScript is a dynamic computer programming language. It is lightweight and most commonly used as a part of web pages, whose implementations allow client-side script to interact with the user and make dynamic pages. It is an interpreted programming language with object-oriented capabilities.
JavaScript was first known as LiveScript, but Netscape changed its name to JavaScript, possibly because of the excitement being generated by Java. JavaScript made its first appearance in Netscape 2.0 in 1995 with the name LiveScript. The general-purpose core of the language has been embedded in Netscape, Internet Explorer, and other web browsers.
Complementary to and integrated with HTML.
Open and cross-platform 

*/

// JavaScript Values
// The JavaScript syntax defines two types of values;
 
// Fixed values are called Literals.
// Variable values are called Variables.

//Using console in javascript

{
    console.log("Hello World");
    console.log("hello javascript");
    console.log(80);
    var a=50;
    var box=60;
    var Box=70;
    console.log(a);
}

// javascript language case-sensitive 

// variable in javascript

{
    names="Css";
    console.log(names);
    var names="brinza";
    console.log(names);
    
    var Names="foo";
    var names="Javascript";
    console.log(names);
    
    var thisis=15;
    var thatis=45;
    console.log(thatis/thisis);
    
    var box1="toys";
    var box1="cloths";
    console.log(box1);
}

// new html element add in though javascript

{
    var newelement=document.createElement("h1");
    newelement.textContent="hello world";
    document.body.appendChild(newelement);
    
    var newelement=document.createElement("marquee");
    newelement.textContent="hello world";
    document.body.appendChild(newelement);
    
    var newelement=document.createElement("p");
    newelement.textContent="how are you!";
    document.body.appendChild(newelement);
}


// window alert() in javascript

{
    window.alert("hello world");
    alert("how are you!");
    alert('pause!');
}


// windows prompt() in javascript

{
    var age=prompt('how old are you!');
    var names= prompt('what is your name');
    var input=prompt('how are you');
}


//Using the DOM API

{
    var a=40;
    var b="hey, i am javascript don't afraid of me."
    var b=30;
    document.getElementById("demo1").innerHTML=a;
    document.getElementById("demo2").innerHTML=b;
}

//let variable ( blockscope variables)

{
    let boxx1="toys1";
    let boxx2="cloths1";
        boxx1="toys2";
        boxx2="cloths2";
        boxx2="foo";
    document.getElementById("demo3").innerHTML=boxx1;
}

//const variable ( blockscope variables)

{
    const toys="bus";
    const toys1="car";
    document.getElementById("demo4").innerHTML=toys;
}

//document.write('hello javascript');

// js comments

// single-line comments

/* multi-line comments */


/*  

Name must start with a letter (a to z or A to Z), underscore( _ ), or dollar( $ ) sign.
After first letter we can use digits (0 to 9), for example value1.
JavaScript variables are case sensitive, for example x and X are different variables.

*/





